export const SITE = {
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://marlongacrama.com",
  name: "marlon gacrama jr",
  shortName: "marlon g.",
  title: "marlon gacrama jr — full-stack & ai engineer",
  tagline: "full-stack & ai engineer",
  description:
    "marlon gacrama jr — full-stack & ai engineer based in cebu, philippines. building agentic systems, voice agents, and end-to-end web products with next.js, react, node, and the openai / claude / langchain stack.",
  locale: "en_US",
  email: "maruronu@gmail.com",
  phone: "+63 939 681 0206",
  location: {
    city: "Cebu City",
    region: "Cebu",
    country: "Philippines",
    countryCode: "PH",
  },
  social: {
    github: "https://github.com/",
    linkedin: "https://linkedin.com/",
  },
  keywords: [
    "marlon gacrama",
    "marlon gacrama jr",
    "full-stack engineer",
    "ai engineer",
    "agentic ai",
    "voice agents",
    "next.js developer",
    "react developer",
    "typescript",
    "node.js",
    "openai",
    "claude",
    "langchain",
    "n8n",
    "make.com",
    "philippines developer",
    "cebu developer",
    "freelance developer",
    "remote developer",
  ],
} as const;
