import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { nullFont } from "./styles/fonts";
import Footer from "./components/Footer";
import Navigation from "./components/Navigation";
import { Providers } from "./providers";
import Socials from "./components/Socials";
import "./globals.css";

const OpenSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${OpenSans.variable} ${nullFont.variable} antialiased`}>
        <Navigation />
        <Providers>{children}</Providers>
        <Socials />
        <Footer />
      </body>
    </html>
  );
}
